### ISSUE TITLE
update_from_request method on boolean variables not work

### ISSUE THREAD

**Issue by mahdi13** [pylover/restfulpy#26]
For exp, when we want to change is_active value from webservice, update_from_request method parse value as string. Then when we reach to this method:
```
self.activated_at = (datetime.now() if v else None)
```
it will always set is_active True, because `v` is actually string instead of bool and the above condition is always `True`

**Comment by pylover** [comment]
We have a lot of tests which updates the is_active flag.

**Comment by pylover** [comment]
I cannot reproduce the issue

**Comment by pylover** [comment]
```python
        self.assertNotIn('password', result)
        self.assertDictContainsSubset(result, {
            'email': email,
            'firstName': 'a first name',
            'lastName': 'a last name',
            'isActive': True,
            'modifiedAt': None,
            'phone': '00123232323',
            'removedAt': None,
            'type': 'salesman'
        })
```

**Comment by pylover** [comment]
I found it. 

It's because of the `is_active` is not a real property, it's a synonym. So we should handle it where the is_active is defined. I mean the `mixines.py`
