### ISSUE TITLE
Parse SqlAlchemy exceptions and decide how to handle violations

### ISSUE THREAD

**Issue by memlucky71** [pylover/restfulpy#29]
[PostgreSQL Error Codes](https://www.postgresql.org/docs/9.1/static/errcodes-appendix.html)

**Comment by memlucky71** [comment]
pylover/restfulpy#29

**Comment by mahdi13** [comment]
Some of my tasks are pending on this issue, what is it's current state?

**Comment by pylover** [comment]
Mmm, Nothing yet, But I'll implement it in short matter of time, Thank's for reminding.
