### ISSUE TITLE
Access group for columns [feature-request]

### ISSUE THREAD

**Issue by meyt** [pylover/restfulpy#83]
Currently restfulpy.orm have `protected` and `readonly` states for columns access control. 
this is okey until i want to have more control to output per client access. for example super users can access to all informations about any users. but normal users just can read some fields like nickname of another users.
For handling this situation, i think we can define `protected` and `readonly` with multiple values.

> Not set = Don't need to any control
> True = Affect anywhere
> ['super_user'] = Just affect on super users 
> ['normal_user', 'manager_user'] = Affect on Super users and Manageres

at implementation we just need set current access group in request context and affect it on output. #82

**Comment by pylover** [comment]
We have a validator decorator, It's a good practice to control request and responses.

This is just an idea to implement such kind of features. 

``` python
@json(exclude=['field1], ....)
def get(self):
    return some_object
```

**Comment by meyt** [comment]
It seems not work inside of relationships, e.g: users model have relation to their girlfriends, in output we don't want share user.girlfriends.address and phone number to normal users.

**Comment by pylover** [comment]
So, exclude them. that's it

**Comment by meyt** [comment]
also we must define excludes on every controller we used that model. it's not close to restfulpy awesomeness.

**Comment by pylover** [comment]
No, The best way is to use decorators. restfulpy awesomeness is: `the controllers are callables just like actions`. so you can decorate the whole controller. Huh

**Comment by meyt** [comment]
> So, exclude them. that's it

how ? 
```
@json(exclude=['email', 'mobile', 'grilfriends.address', 'girlfriends.mobile'...])
```
oh, i look some controllers with 10line of exclusions as decorator on top of that!

**Comment by pylover** [comment]
have you seen the validator decorator ?

**Comment by pylover** [comment]
Is there any technical problem if a decorator definition gets big? I think it increases  the performance,

Again, please check the validator decorator

**Comment by pylover** [comment]
I'm wondering how you thinking about python.

**Comment by pylover** [comment]
```python
    @json
    @validate_form(exclude=['excludedParamForAll'],
                   client={'exclude': ['excludedParamForClient']},
                   admin={'exclude': ['excludedParamForAdmin']})
    def post(self):
        result = copy.deepcopy(context.form)
        result.update(context.query_string)
        return result
```

**Comment by meyt** [comment]
i'm not talk about decortor performance. i just described my idea about how to group field access to namespaces and use it where i need.

**Comment by meyt** [comment]
#82 with little edition, can also set access group on decorator for being pythonic.

**Comment by pylover** [comment]
Yes, of-course, but I promote the performance here, to make you happy about my idea.

Another approach is: I wish your pull request will be completely modular. and please implement your idea in an isolated area without manipulating the core.

**Comment by pylover** [comment]
You're trying to find a hard solution for a simple problem.

**Comment by meyt** [comment]
```python
@json
@authorize
@User.expose
def get(user_id: int):
    user = db.query(User).filter_by(id=user_id).first()

    if context.identity.role == 'normal_user':
        if user.is_friend_of(context.identity.id):
            User.set_access_group('friend_normal_user')
            return user  # exclude fields related to friend_normal_user group 

        else:
            User.set_access_group('public_normal_user')
            return user  # exclude fields related to public_normal_user group 
        
    return user  # with all fields


```

**Comment by meyt** [comment]
how you can handle it with decorator simpler than this?

**Comment by pylover** [comment]
```python
    @validate_form(exclude=['excludedParamForAll'],
                   client={'exclude': ['excludedParamForClient']},
                   admin={'exclude': ['excludedParamForAdmin']})
```

**Comment by pylover** [comment]
Are you kidding ?

**Comment by meyt** [comment]
please, there is conditional exclusions!

**Comment by pylover** [comment]
Wow, I know, please see the `admin` and `client` in my example

**Comment by meyt** [comment]
i mean about this part, it can have more conditional than this:
```python
...
if user.is_friend_of(context.identity.id):
  if user.eat_breakfest_with(context.identy.id):
...
```

**Comment by pylover** [comment]
You have to implement this in your controller, Framework is not developed for such kind of purposes.
This is an exceptional situation.

But, there are several better ideas for implementing it. You choose the worst of them.

A good practice is to use rule-engine pattern. and or passing/registering callable to determine the permission for a field or whole response. 

You can not fit your personal ideas or requirements by manipulation a community-level framework.

**Comment by pylover** [comment]
I think a bad architecture and design is forcing you to do that.
